apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Slack Bots API
  description: "Slack\x19s bot APIs let you build apps that live in Slack and automate work by listening for events and taking actions in conversations. Using the Web API, your bot can post and schedule messages, reply in threads, manage channels, look up users, and access files or reactions; the Events API delivers message, reaction, and workflow events to your server so you can respond in real time. Bots can power slash commands, message shortcuts, and interactive UI elements (buttons, menus, modals built with Block Kit), and they can open modals or update messages dynamically. Installation and access are controlled via OAuth 2.0 scopes, with bot tokens used to authenticate API calls; you can receive events over HTTPS or via Socket Mode if you don\x19t host a public endpoint. Together, these capabilities let you create assistants that answer questions, route approvals, connect external services, and streamline team processes directly inside Slack."
  tags: []
  links:
    - icon: code
      url: https://github.com/naftiko/slack-sandbox
spec:
  type: openapi
  lifecycle: experimental
  owner: kinlane@naftiko.io
  definition: |
    openapi: 3.1.0
    info:
      title: slack-bots-api
      description: "Slack\x19s bot APIs let you build apps that live in Slack and automate work by listening for events and taking actions in conversations. Using the Web API, your bot can post and schedule messages, reply in threads, manage channels, look up users, and access files or reactions; the Events API delivers message, reaction, and workflow events to your server so you can respond in real time. Bots can power slash commands, message shortcuts, and interactive UI elements (buttons, menus, modals built with Block Kit), and they can open modals or update messages dynamically. Installation and access are controlled via OAuth 2.0 scopes, with bot tokens used to authenticate API calls; you can receive events over HTTPS or via Socket Mode if you don\x19t host a public endpoint. Together, these capabilities let you create assistants that answer questions, route approvals, connect external services, and streamline team processes directly inside Slack."
      version: 1.0.0
      contact:
        name: Slack API Support
        url: https://api.slack.com/support
      license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
    servers:
      - url: https://slack.com/api
        description: Slack API Production Server
    paths:
      /bots.info:
        get:
          tags:
            - Get
            - Bots
          description: Gets information about a bot user.
          externalDocs:
            description: API method documentation
            url: https://api.slack.com/methods/bots.info
          operationId: getBotsInfo
          parameters:
            - name: token
              in: query
              description: 'Authentication token. Requires scope: `users:read`'
              required: true
              schema:
                type: string
            - name: bot
              in: query
              description: Bot user to get info on
              schema:
                type: string
          responses:
            '200':
              description: When successful, returns bot info by bot ID.
              content:
                application/json:
                  schema:
                    title: bots.info schema
                    required:
                      - bot
                      - ok
                    type: object
                    properties:
                      bot:
                        type: object
                        additionalProperties: false
                      ok:
                        $ref: '#/components/schemas/defs_ok_true'
                    additionalProperties: false
                    description: Schema for successful response from bots.info method
                  example:
                    bot:
                      app_id: A161CLERW
                      deleted: false
                      icons:
                        image_36: https://...
                        image_48: https://...
                        image_72: https://...
                      id: B061F7JD2
                      name: beforebot
                      updated: 1449272004
                      user_id: U012ABCDEF
                    ok: true
            default:
              description: When no bot can be found, it returns an error.
              content:
                application/json:
                  schema:
                    title: bots.info error schema
                    required:
                      - error
                      - ok
                    type: object
                    properties:
                      callstack:
                        type: string
                        description: 'Note: PHP callstack is only visible in dev/qa'
                      error:
                        type: string
                        enum:
                          - bot_not_found
                          - not_authed
                          - invalid_auth
                          - account_inactive
                          - token_revoked
                          - no_permission
                          - org_login_required
                          - invalid_arg_name
                          - invalid_array_arg
                          - invalid_charset
                          - invalid_form_data
                          - invalid_post_type
                          - missing_post_type
                          - team_added_to_org
                          - invalid_json
                          - json_not_object
                          - request_timeout
                          - upgrade_required
                          - fatal_error
                      ok:
                        $ref: '#/components/schemas/defs_ok_false'
                    additionalProperties: false
                    description: Schema for error response from bots.info method
                  example:
                    error: bot_not_found
                    ok: false
          security:
            - slackAuth:
                - users:read
          summary: Get  Bots Info
          x-api-evangelist-processing:
            GenerateOperationSummariesFromPath: true
            PascalCaseOperationSummaries: true
            CaselCaseOperationIds: true
            ChooseTags: true
    components:
      schemas: {}
